id = "not-too-shabby"
name = "NotTooShabby"
description = "Pretty much fine dark theme for Zed"
version = "0.1.0"
schema_version = 1
authors = ["Stas Syritsyn <staleo@hey.com>"]
repository = "https://github.com/staleo/zed-nottooshabby-theme"